services:
  libraryapp:
    image: sairaj1271/lmspro
    ports:
      - "9080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lmsdb
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lmspass
    ports:
      - "3307:3306"
